// See https://aka.ms/new-console-template for more information
Console.WriteLine("Skriv fem tall åt gång och jag kommer skriva dom i omvänd ordning");
int[] v = new int[5];
string str1 = Console.ReadLine();
v[0] = int.Parse(str1);
Console.WriteLine("Skriv de andra tal");
string str2 = Console.ReadLine();
v[1] = int.Parse(str2);
Console.WriteLine("Skriv den tredje");
string str3 = Console.ReadLine();
v[2] = int.Parse(str3);
Console.WriteLine("Skriv den fjärde");
string str4 = Console.ReadLine();
v[3] = int.Parse(str4);
Console.WriteLine("Skriv den femte");
string str5 = Console.ReadLine();
v[4] = int.Parse(str5);
Console.WriteLine("talet i omvänd ordning är");
Console.WriteLine(v[4]);
Console.WriteLine(v[3]);
Console.WriteLine(v[2]);
Console.WriteLine(v[1]);
Console.WriteLine(v[0]);
